/**
 * Test that plugin source files are TypeScript.
 *
 * Plugins must be TypeScript (.ts) files as the canonical source.
 * Compiled .js files are generated by `npm run build:modules` and
 * must always have a corresponding .ts source file.
 *
 * This test catches:
 * 1. Plugins with .js files but no .ts source
 * 2. Missing index.ts files
 */

import { describe, it, expect } from "vitest";
import { readdirSync, existsSync, statSync } from "fs";
import { join } from "path";

const PLUGINS_DIR = join(import.meta.dirname, "..", "plugins");

// Get all plugin directories (excluding 'shared' which contains utilities)
function getPluginDirs(): string[] {
  if (!existsSync(PLUGINS_DIR)) return [];

  return readdirSync(PLUGINS_DIR).filter((name) => {
    const dir = join(PLUGINS_DIR, name);
    // Must be a directory and have a plugin.json
    return statSync(dir).isDirectory() && existsSync(join(dir, "plugin.json"));
  });
}

describe("plugin source files", () => {
  const pluginDirs = getPluginDirs();

  if (pluginDirs.length === 0) {
    it.skip("no plugins found", () => {});
    return;
  }

  for (const pluginName of pluginDirs) {
    const pluginDir = join(PLUGINS_DIR, pluginName);
    const tsPath = join(pluginDir, "index.ts");

    it(`${pluginName}: has index.ts source file`, () => {
      expect(
        existsSync(tsPath),
        `Plugin ${pluginName} is missing index.ts. ` +
          `Plugins must be written in TypeScript.`,
      ).toBe(true);
    });
  }
});

describe("test fixture plugins", () => {
  const fixturesDir = join(import.meta.dirname, "fixtures");

  if (!existsSync(fixturesDir)) {
    it.skip("no fixtures directory", () => {});
    return;
  }

  // Get directories that have plugin.json (i.e., are plugin fixtures)
  const fixtureDirs = readdirSync(fixturesDir).filter((name) => {
    const dir = join(fixturesDir, name);
    return statSync(dir).isDirectory() && existsSync(join(dir, "plugin.json"));
  });

  for (const fixtureName of fixtureDirs) {
    const fixtureDir = join(fixturesDir, fixtureName);
    const tsPath = join(fixtureDir, "index.ts");
    const jsPath = join(fixtureDir, "index.js");

    // Skip fixtures that are intentionally missing index files (like broken-plugin)
    const hasAnyIndex = existsSync(tsPath) || existsSync(jsPath);
    if (!hasAnyIndex) {
      it(`fixture ${fixtureName}: intentionally has no index file`, () => {
        // This is fine - some fixtures test error handling for missing files
        expect(true).toBe(true);
      });
      continue;
    }

    it(`fixture ${fixtureName}: has index.ts`, () => {
      expect(existsSync(tsPath)).toBe(true);
    });
  }
});

describe("shared plugin utilities", () => {
  const sharedDir = join(PLUGINS_DIR, "shared");

  if (!existsSync(sharedDir)) {
    it.skip("no shared utilities directory", () => {});
    return;
  }

  const files = readdirSync(sharedDir);
  const tsFiles = files.filter((f) => f.endsWith(".ts"));
  const jsFiles = files.filter((f) => f.endsWith(".js"));

  it("shared utilities are TypeScript", () => {
    expect(
      tsFiles.length,
      "No .ts files found in plugins/shared/",
    ).toBeGreaterThan(0);
  });

  it("every .js in shared has a .ts source", () => {
    for (const jsFile of jsFiles) {
      const tsFile = jsFile.replace(/\.js$/, ".ts");
      expect(
        tsFiles,
        `${jsFile} in plugins/shared/ has no corresponding .ts source`,
      ).toContain(tsFile);
    }
  });
});
